name: CI build and push

on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

jobs:
  get-pom-properties:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: query-pom
      name: Get properties from POM
      # Query POM for core and image version and save as output parameter
      run: |
        CORE_VERSION="$(mvn help:evaluate -Dexpression=io.cryostat.core.version -q -DforceStdout)"
        echo "::set-output name=core-version::v$CORE_VERSION"
        IMAGE_VERSION="$(mvn help:evaluate -Dexpression=cryostat.imageVersion -q -DforceStdout)"
        echo "::set-output name=image-version::$IMAGE_VERSION"
    outputs:
      core-version: ${{ steps.query-pom.outputs.core-version }}
      image-version: ${{ steps.query-pom.outputs.image-version }}

  build-deps:
    runs-on: ubuntu-latest
    needs: [get-pom-properties]
    steps:
    - uses: actions/checkout@v2
      with:
        repository: cryostatio/cryostat-core
        ref: ${{ needs.get-pom-properties.outputs.core-version }}
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: restore
    - run: mvn -B -U -DskipTests=true clean install
    - uses: actions/upload-artifact@v2
      with:
        name: cryostat-core
        path: /home/runner/.m2/repository/io/cryostat/cryostat-core/
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: save

  build:
    runs-on: ubuntu-latest
    needs: [get-pom-properties, build-deps]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: restore
    - uses: actions/download-artifact@v2
      with:
        name: cryostat-core
        path: /home/runner/.m2/repository/io/cryostat/cryostat-core/
    - run: git submodule init
    - run: git submodule update
    - run: mvn -B -U clean verify
    - uses: skjolber/maven-cache-github-action@v1
      with:
        step: save
    - name: Push to quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: cryostat
        tags: >
          ${{ needs.get-pom-properties.outputs.image-version }}
        registry: quay.io/ebaron
        username: ebaron+bot
        password: ${{ secrets.REGISTRY_PASSWORD }}
      if: ${{ github.event_name == 'push' && github.repository_owner == 'ebaron' }}
    - name: Print image URL
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
      if: ${{ github.event_name == 'push' && github.repository_owner == 'ebaron' }}
